---
`---
title: "SI time model"
format: html
editor: visual
---

## Appendix

These arguments make a strong assumption: that high time discounting is dysfunctional. However, even if focusing on the present is associated with worse outcomes in life, it does not imply that it is always detrimental [@daly2005; @frankenhuis2020]. This is particularly questionable in situations of poverty: as @frankenhuis2020 put it, "some people obviously need to use their resources immediately to meet basic needs (e.g., food, shelter) or live in conditions in which future rewards are unlikely to materialize." (p. 17).

### Time discounting as a rational response to a state of poverty

A second body of literature has proposed reasons why focusing on the short-term could be at least a "partly rational" response to poverty - or, equivalently, an evolutionary adaptation to resource scarcity through phenotypic plasticity [@pepper2017; @mell2019; @boon-falleur2024]. Here, this is the view we adopt. As @frankenhuis2020 quote implies, such explanations can be divided in two classes, namely "collection risks" and "opportunity costs" [@stephens2002; @fawcett2012]. We also focus on poverty as a "state", rather than a "harshness", i.e. an environment-level stable parameter. For this reason, we do not mention most of the models reviewed in @fenneman2022, as they study what environmental conditions favor impulsivity, instead of state.

### Collection risks

The first class of explanations focuses on "collection risks", the probability that the future reward will not be cashed in. The most natural example of a collection risk is mortality: if one is unlikely to be alive tomorrow, it makes little sense to wait for a larger reward. Empirically, low-SES individuals experience higher mortality risks throughout their lifespan, which should lead them to discount the future more steeply. This rational has been widely used to explain the social gradient in time preference, in particular in evolutionary psychology [@griskevicius2011; @griskevicius2011b; @pepper2017; @baumard2019].

Recently, it has however been argued that mortality risks are too small by order of magnitudes to account for the amount of time discounting [@riis-vestergaard2017; @mell2017]. In @riis-vestergaard2017, the authors conclude that only 0.13% of the observed discounting can be attributed to mortality. Therefore, it is hard to see how the social gradient in mortality could account for the large social gradient in time discounting. It remains possible that poverty increases collection risks unrelated to mortality: poverty could create a higher probability that something happens to the reward before it can be cashed in [@riis-vestergaard2017]. This brings an empirical question that remains open: to what extent do collection risks differ between SES? Furthermore, collection risk is not a 'state' variable, but rather an environment parameter, plausibly statistically related to poverty, likely to be quite stable on short term scales. It can therefore not explain the fact that a state like hunger increases time discounting in humans [@wang2010; @allen2021; @kirk1997] + HEROIN GIORDANO.

Empirically, ethnographers have noted striking heterogeneities in time orientation inside a single neighbourhood CODE OF THE STREETS, decent vs street.

### Waiting costs and basic needs

In any case, collection risks are only one side of the problem. When deciding whether to wait for a larger reward, one should not only consider the probability that the future reward is obtained, but also what the individual would do with the resources in the meantime. This brings a second question: can poverty increase the "opportunity costs" of resources? Along with the title quote, several verbal arguments claim that it is the case: @frankenhuis2020 argue that "some people obviously need to use their resources immediately to meet basic needs (e.g., food, shelter)" (p. 17), while @haushoferNegativeIncomeShocks2013 propose that "people may simply have to put food on the table today, and therefore appear impatient" (p. 2).

It is indeed obvious that situations of poverty increase the utility of consuming resources now: this follows from the widely accepted assumption of diminishing marginal utility. However, this does not suffice to obtain a social gradient: the optimal level of time discounting depends not only on the value of present consumption, but also on the (expected) value of future consumption, which should also increase in situations of poverty. If she expects to need the resources even more badly tomorrow, she should actually save them. The reasoning is only valid if the resources matter for survival, for instance if the individual has a chance to die by starvation otherwise. This situation, where insufficient consumption increases mortality, has for instance been formalised by @chavas2013 - who interestingly, calls this result a mere "conjecture", since it follows so directly from the assumptions.

If survival is not at stake, though, the reasoning does not stand. Yet, even if survival is guaranteed, there are still "needs" that one could consider as "basic", in the sense that it is particularly painful not to meet them. There, verbal theories still predict that not being able to meet them should produce impulsivity [@haushoferNegativeIncomeShocks2013; @frankenhuis2020]. There have been, to our knowledge, two attempts to formalise this argument:

-   In economics, @epper2015 proposed that "liquidity constraints" could produce impulsive decisions. The reasoning is the following. If consumption has diminishing marginal utility, one should smooth his consumption over time, and ideally consume the exact same amount at every time period of his life. This is called the 'permanent income hypothesis', a classical idea in economics [@friedman1957]. Now, if she is poorer at some moments of her life, and if there exists a frictionless financial market, she should borrow at those moments to maintain a stable 'consumption path'. In reality, though, it can be hard to borrow, in particular for individuals with low or unpredictable incomes. Then, an individual who has unusually little resources on this time period would like to consume more, but can not: he is "liquidity constrained". In this situation, he would clearly prefer 1€ now to 1€ later. In @haushoferNegativeIncomeShocks2013, this model is interpreted in terms of basic needs: "people may simply have to put food on the table today, and therefore appear impatient" (p. 2).

-   @mell2021 proposed that poverty was analogous to being a young, growing startup company. Resources are not only useful for consumption, but also for investing in his human capital, and generate more resources thereafter. Like a startup, an individual with little capital has a larger potential to increase his productivity - assuming that capital has diminishing returns on productivity. Therefore, such an individual should prefer a small and sooner reward because he could, in the meantime, use it to grow faster. In contrast, a richer individual has a smaller scope for improving his productivity, and should therefore be more indifferent.

Both models make an important assumption: they posit that those individuals "expect their income to rise in a not so distant future" [@epper2015, p. 1]. Otherwise, their prediction reverse: "If a(n) (relatively poor) agent expects her income to decline substantially in the not so distant future \[...\], predicted discount rates will lie below the agent's pure rate of time preference" [@epper2015, p. 19]. In @mell2019, the model is introduced by the same citation from the TV show *Atlanta* that we used in the title ("poor people don't have time for investments, because poor people are too busy trying not to be poor! I need to eat today, not in September..."). Though, one also needs to eat tomorrow, and the model only yields the desired prediction if it assumes that once they have eaten today, they will will instead have to meet a less crucial need tomorrow, like accomodation.

Thus, the two models implicitly assume that situations of poverty are temporary, and that things have good chances to improve. Therefore, it is hard to see how they apply to the "truly disadvantaged" [@wilson2012] who, on the contrary, tend to (i) have little chance to exit poverty [@banerjee2012] and (ii) to be very pessimistic about their future [@brezina2008]. In an ethnography of Saint Louis offenders who combined financial "desperation" (p. 20) with a "present orientation" (p.1), @dickinson2024 reported that "offenders view their lives as fatalistic time tracks owing to financial insecurity and unstable futures" (p.1). ADD CODE OF THE STREETS, street oriented individuals "lack of hope for the future".

We thus consider that the literature lacks a model studying the effect of a "basic needs" assumption on time preferences, in the absence of improvement prospects. In this case, intuition and the empirical record still suggest that individuals discount the future steeply, and the literature lacks an argument to justify it.

Fig S1: utility functions

Fig S2: Heatmaps
