---
title: "'I need to eat today, not in September': a simple model of intertemporal decisions under a desperation threshold"
author: "Benoit de Courson"
date: "2024-04-23"
header-includes:
  - \usepackage[english]{babel}
#  - \usepackage[letterpaper,top=2cm,bottom=2cm,left=3cm,right=3cm,marginparwidth=1.75cm]{geometry}
  - \usepackage{amsmath}
  - \usepackage{graphicx}
  - \usepackage[colorlinks=true, allcolors=blue]{hyperref}
  - \usepackage{tikz}
  - \usepackage{ebgaramond}
  - \setlength{\parindent}{1cm}
output:
  pdf_document: 
    latex_engine: xelatex
    number_sections: true
#bibliography: biblio.bib
bibliography: references.bib
---

# Introduction

Time discounting - the devaluation of future consequences - shows a clear gradient with economic resources [@reimers2009; @green1996; @haushofer2014]. Concretely, low-income individuals are often observed to refuse high return investment opportunities and to accept loans with prohibitive interest rates [@banerjee2007]. In a recent review [@haushofer], higher time discounting actually appeared as the only well established causal effect of poverty on decision making. This effect is of interest to several disciplines, including economics [@lawrance1991], sociology [@duvoux2023] and psychology [@haushofer2014]. It has important implications: it has been proposed (i) as the cause of the 'behavioural constellation of poverty', the ensemble of behavioral specificities accross domains that are commonly found among individuals in situations of poverty [@pepper2017], (ii) as a possible reason why people tend to be stuck in poverty [@haushofer2014], and (iii) as a reason for the higher prevalence of crime - a behaviour that often brings short-term benefits and potential long-term legal troubles - among deprived populations [@pepper2017; @brezina2008].

Yet, in stark contrast with the mostly settled empirical case, it remains highly debated why individuals do so. Theoretical work in this question can be traced back to @fisher1930, who claimed that "Poverty [...] increases the want for immediate income even more than it increases the want for future income. [...] This influence of poverty is partly rational, because of the importance, by supplying present needs, of keeping up the continuity of life and thus maintaining the ability to cope with the future; and partly irrational, because the pressure of present needs blinds a person to the needs of the future" (p. 72).

Since, several bodies of literature have proposed theoretical explanations for this social gradient. We can first divide these explanations in two classes, insisting respectively on the "rational" and "irrational" aspects.

## Time discounting as an irrational decision

A first body of literature sees impulsive decision making as an irrational decision, induced in situations of poverty by a degraded decision making. Several mechanisms have been proposed for this: poverty could lead to a lower cognitive capacity due to stress [@haushofer2014; @mani2013], or lead to an ego-depletion phenomenon [@spears2011] -- but since, both mechanisms have shown replication issues [@gonzález-arango2022; @hagger2016; @haushofer]. Recently, @laajaj2017 proposed that not thinking about the future could be, as @banerjee2007 (p. 165) put it, "emotionally wise" in situations of poverty, "to reduce the distress generated by the anticipation of future hardship" (p. 187).

These arguments make a strong assumption: that high time discounting is dysfunctional. However, even if focusing on the present is associated with worse outcomes in life, it does not imply that it is always detrimental [@daly2005; @frankenhuis2020]. This might in particular be false in situations of poverty: as @frankenhuis2020 put it, "some people obviously need to use their resources immediately to meet basic needs (e.g., food, shelter) or live in conditions in which future rewards are unlikely to materialize." (p. 17).

## Time discounting as a rational response to a state of poverty

Therefore, a second body of literature has proposed reasons why focusing on the short-term could be at least "partly rational" response to poverty - or, equivalently, an evolutionary adaptation to resource scarcity through phenotypic plasticity [@pepper2017; @mell2019; @boon-falleur2024]. Here, this is the view we focus on. As @frankenhuis2020 quote implies, such explanations can be divided in two classes, namely "collection risks" and "opportunity costs" [@stephens2002; @fawcett2012]. We also focus on poverty as a "state", rather than a "harshness", i.e. an environment-level stable parameter. For this reason, we do not mention most of the models reviewed in @fenneman2022, as they study what environmental conditions favor impulsivity, instead of state.

### Collection risks

The first class of explanations focuses on "collection risks", the probability that the future reward will not be cashed in. The most natural example of a collection risk is mortality: if one is unlikely to be alive tomorrow, it makes little sense to wait for a larger reward. Empirically, low-SES individuals experience higher mortality risks throughout their lifespan, which should lead them to discount the future more steeply. This rational has been widely used to explain the social gradient in time preference, in particular in evolutionary psychology [@griskevicius2011; @griskevicius2011b; @pepper2017; @baumard2019].

Recently, it has however been argued that mortality risks are too small by order of magnitudes to account for the amount of time discounting [@riis-vestergaard2017; @mell2017]. In @riis-vestergaard2017, the authors conclude that only 0.13% of the observed discounting can be attributed to mortality. Therefore, it is hard to see how the social gradient in mortality could account for the large social gradient in time discounting. It remains possible that poverty increases collection risks unrelated to mortality: poverty could create a higher probability that something happens to the reward before it can be cashed in [@riis-vestergaard2017]. This brings an empirical question that remains open: to what extent do collection risks differ between SES? Furthermore, collection risk is not a 'state' variable, but rather an environment parameter, plausibly statistically related to poverty, but quite stable on short term scales. It can therefore not explain the fact that a state like hunger increases time discounting in humans [@wang2010; @allen2021; @kirk1997] + HEROIN GIORDANO.

### Waiting costs and basic needs

In any case, collection risks are only one side of the problem. When deciding whether to wait for a larger reward, one should not only consider the probability that the future reward is obtained, but also what the individual would do with the resources in the meantime. This brings a second question: can poverty increase the "opportunity costs" of resources? Along with the title quote, several verbal arguments claim that it is the case: @frankenhuis2020 argue that "some people obviously need to use their resources immediately to meet basic needs (e.g., food, shelter)" (p. 17), while @haushoferNegativeIncomeShocks2013 propose that "people may simply have to put food on the table today, and therefore appear impatient" (p. 2).

It is indeed obvious that situations of poverty increase the utility of consuming resources now: this follows from the widely accepted assumption of diminishing marginal utility. However, this does not suffice to obtain a social gradient: the optimal level of time discounting depends not only on the value of present consumption, but also on the (expected) value of future consumption, which should also increase in situations of poverty. If she expects to need the resources even more badly tomorrow, she should actually save them. The reasoning is only valid if the resources matter for survival, for instance if the individual has a chance to die by starvation otherwise. This situation, where insufficient consumption increases mortality, has for instance been formalised by @chavas2013 - who interestingly, calls this result a mere "conjecture", since it follows so directly from the assumptions.

If survival is not at stake, though, the reasoning does not stand. Yet, even if survival is guaranteed, there are still "needs" that one could consider as "basic", in the sense that it is particularly painful not to meet them. There, verbal theories still predict that not being able to meet them should produce impulsivity [@haushoferNegativeIncomeShocks2013; @frankenhuis2020]. There have been, to our knowledge, two attempts to formalise this argument:

-   In economics, @epper2015 proposed that "liquidity constraints" could produce impulsive decisions. The reasoning is the following. If consumption has diminishing marginal utility, one should smooth his consumption over time, and ideally consume the exact same amount at every time period of his life. This is called the 'permanent income hypothesis', a classical idea in economics [@friedman1957]. Now, if she is poorer at some moments of her life, and if there exists a frictionless financial market, she should borrow at those moments to maintain a stable 'consumption path'. In reality, though, it can be hard to borrow, in particular for individuals with low or unpredictable incomes. Then, an individual who has unusually little resources on this time period would like to consume more, but can not: he is "liquidity constrained". In this situation, he would clearly prefer 1€ now to 1€ later. In @haushoferNegativeIncomeShocks2013, this model is interpreted in terms of basic needs: "people may simply have to put food on the table today, and therefore appear impatient" (p. 2).

-   @mell2021 proposed that poverty was analogous to being a young, growing startup company. Resources are not only useful for consumption, but also for investing in his human capital, and generate more resources thereafter. Like a startup, an individual with little capital has a larger potential to increase his productivity - assuming that capital has diminishing returns on productivity. Therefore, such an individual should prefer a small and sooner reward because he could, in the meantime, use it to grow faster. In contrast, a richer individual has a smaller scope for improving his productivity, and should therefore be more indifferent.

Both models make an important assumption: they posit that those individuals "expect their income to rise in a not so distant future" [@epper2015, p. 1]. Otherwise, their prediction reverse: "If a(n) (relatively poor) agent expects her income to decline substantially in the not so distant future [...], predicted discount rates will lie below the agent's pure rate of time preference" [@epper2015, p. 19]. In @mell2019, the model is introduced by the same citation from the TV show *Atlanta* that we used in the title ("poor people don't have time for investments, because poor people are too busy trying not to be poor! I need to eat today, not in September..."). Though, one also needs to eat tomorrow, and the model only yields the desired prediction if it assumes that once they have eaten today, they will will instead have to meet a less crucial need tomorrow, like accomodation. [Daniel asked me to reanalyse the model to make sure my assessment was correct. I had a chat with Jean-Baptiste, and it is clear that if productivity is not rising over time, time preference is only determined by extrinsic mortality. If mortality is independent from poverty, then it should have no effect, and if it is, then it is a "collection risks" argument]

Thus, the two models implicitly assume that situations of poverty are temporary, and that things have good chances to improve. Therefore, it is hard to see how they apply to the "truly disadvantaged" [@wilson2012] who, on the contrary, tend to (i) have little chance to exit poverty [@banerjee2012] and (ii) to be very pessimistic about their future [@brezina2008]. In an ethnography of Saint Louis offenders who combined financial "desperation" (p. 20) with a "present orientation" (p.1), @dickinson2024 reported that "offenders view their lives as fatalistic time tracks owing to financial insecurity and unstable futures" (p.1).

We thus consider that the literature lacks a model studying the effect of a "basic needs" assumption on time preferences, in the absence of improvement prospects. In this case, intuition and the empirical record still suggest that individuals discount the future steeply, and the literature lacks an argument to justify it.

## My proposition

We propose to use a "desperation threshold" model to represent this situation. We assume that agents have a critical amount of resources, representing "basic needs", above which they try to stay at every time period. Concretely, we assume (i) a "utility cliff" - falling below at any point is very unpleasant - and (ii) a "rock bottom" - being below the threshold for a second time does not hurt as bad as the first time [as Daniel elegantly put it, this can be also be phrased as "the first cut is the deepest"]. For instance, not paying rent can be very detrimental to one's wellbeing, but not paying rent for a second month makes a smaller difference: one risks eviction anyway. Our intuition is that the proximity to the desperation threshold could generate a preference for resources today, which would clearly help to avoid the desperation zone. In contrast, a reward collected in the future could be less useful for two reasons: the individual could (i) have exited the dangerous zone, and not need the resource as badly, and (ii) have stayed below the threshold in between, in which case the "rock bottom" assumption implies that there is little left to save. Then, an individual in situations of poverty could prefer an immediate reward whether he has good or bad prospects: whichever way he moves would make the resource less useful in the future.

We see this model as answering another, inverse, literature gap. There are many "desperation threshold" models in biology, psychology and economics [e.g. @roumasset1971; @stephens1981; @lybbert2007; @barclay; @decourson2021]. Though, they all focus on the consequences of the threshold on risk attitudes, presumably because the result is clear and intuitive. Its effect on time preferences has not yet been studied, possibly because it is less obvious. If the "desperation threshold" exists, though, it might also impact time attitudes, and it is important to understand those consequences even if they are not as straightforward. We only found one model of time preferences (studying mice impulsivity) which includes a threshold (starvation) [@campbell2008]. Though, its effect is unclear, and the model does not allow for state-dependence but only for adapting to environment characteristics.

Finally, the proposed model could help to solve another paradox about criminal behaviour. The time discounting literature states that risk and time are intertwined: the future is treated as unpredictable, whereas the present is known [@epper2024; @andreoni2012]. Then, risk-averse people should prefer immediate (certain) rewards to future (unpredictable) ones. Conversely, risk tolerant people should be more indifferent. Though, individuals engaging in criminal activity accept the risk of a large future cost (being caught and convicted). Empirically, offenders seem to have both high time discounting and risk tolerance [@epperPreferencesPredictWho2022b].

## Dynamics
We model an individual who makes an intertemporal decision. Starting from an initial level of resources $x_0$, he lives through two time periods (denoted 1 and 2). A normally distributed perturbation (mean 0 and variance $\sigma^2$, representing volatility) is added between $x_0$ and $x_1$, then again between $x_1$ and $x_2$. NB: when solving the model, maybe we could try other distributions, to make it analytically tractable.

At time 0, the agent decides between two options:

```{=tex}
\begin{itemize}
    \item Being 'impatient', and gaining $g$ resources immediately, that is between $x_0$ and $x_1$.
    \item Being 'patient', and gaining $(1+r)g$ resources one period later (between $x_1$ and $x_2$). $r$ represents the interest rate.
\end{itemize}
```
```{=tex}
\begin{tikzpicture}[>=stealth, node distance=3cm]

% Nodes
\node (x0) at (0,0) {$x_0$};
\node (x1) at (4,0) {$x_1$};
\node (x2) at (8,0) {$x_2$};


% Arrows
\draw[->] (x0) -- node[below]{$+\mathcal{N}(0, \sigma^2)$} (x1);
\draw[->] (x1) -- node[below]{$+\mathcal{N}(0, \sigma^2)$} (x2);

% Curvy dashed arrows with labels
\draw[->, bend left=45, dashed] (x0) to node[below] {+$g$} node[above] {If impatient} (x1);
\draw[->, bend left=45, dashed] (x1) to node[below] {+$(1+r)g$} node[above] {If patient} (x2);

\end{tikzpicture}
```
\section{Goals of the individual}

The individual wants two things: be as rich as possible at the end of the game (maximise $x_2$) and pay rent at both time period (that is, minimise the probability that $x_1<0$ and $x_2<0$). One more thing: we assume that not paying rent once hurts a lot ($-\alpha)$, not paying it a second time hurts less ($-\beta$, with $0 \le \beta \le \alpha)$: you might already have been evicted, or anyway you are already in trouble with your landlord. This assumption reflects the idea of a 'rock bottom'. Note that the framework includes the case where there is no rock bottom ($\beta = \alpha$) and the case where it is game over after one rent failure ($\beta = 0$).

The utility function is therefore: $$
U(x_1,x_2) = x_2 - \alpha (x_1 < 0 \cup x_2 < 0) - \beta (x_1 < 0 \cap x_2 < 0)
$$

\section{Planned analysis}

For every value of the parameters, we will compute the interest rate $r^\star$ such that the individual is indifferent between patience and impatience, that is, between $g$ resources now and $(1+r)g$ resources later. In particular, we are interested in :

\`\`\`{=tex}

```{=tex}
\begin{itemize}
    \item How $r^\star$ depends on $x_0$, that is, how poverty impacts the willingness to delay the reward. 
    \item To what extent this result depends on the value of $\beta$, that is, on whether there is a rock bottom. We expect that a rock bottom exacerbates impatience under extreme poverty.
    \item How $r^\star$ depends on the volatility $\sigma^2$, possibly in interaction with other parameters. In particular, volatility should increase the risk of not paying rent when $x_0 > 0$, but 
    decrease it when $x < 0$ (just as one should gamble below the threshold but not above in our previous models).
\end{itemize}
```

# Bibliography
