project:
  type: book

book:
  title: "The desperation threshold: a model to explain decisions in poverty"
  subtitle: "De wanhoopsdrempel: een model om beslissingen in armoede te begrijpen"
  author: "Benoît de Courson"
  date: "2025"
  
  chapters:
    - index.qmd
    - intro.qmd
    - violence/violence.qmd
    - model_time/time_draft.qmd
    - empirical_paper/analysis_ccl.qmd
    - bbs/bbs.qmd
    - discussion.qmd
    - references.qmd

  # Optional: Parts for organizing chapters
  # parts:
  #   - part: "Part I: Introduction"
  #     chapters:
  #       - index.qmd
  #       - intro.qmd
  #   - part: "Part II: Main Content"
  #     chapters:
  #       - chapter1.qmd
  #       - chapter2.qmd

format:
  pdf:
    documentclass: scrreprt
    classoption: [notitlepage]
    include-before-body: title.tex
    include-in-header: header.tex
    keep-tex: true
csl: apa.csl
link-citations: true

# Optional: Additional metadata
bibliography: 
  - references.bib # the intro and discussion references
  - model_time/references.bib  
  - empirical_paper/references.bib
  - violence/references.bib
  - bbs/references.bib

# Optional: Execute options
execute:
  freeze: auto


profile:
  single-chapter: # <--- This is the profile name, as a key directly under 'profile:'
    project:
      type: default # Treat it as a standalone document
      render: [] # Don't render anything else from the book
    book: ~ # Nullify book-specific settings for this profile
    format:
      pdf