project:
  type: book

book:
  title: "The desperation threshold model: a framework to understand decisions in poverty"
  author: "Benoît de Courson"
  date: "2025-06-23"
  
  chapters:
    - index.qmd
    - violence/violence.qmd
    - model_time/time_draft.qmd
    - empirical_paper/analysis_ccl.qmd
    - bbs/bbs.qmd
    - discussion.qmd
    - references.qmd

  # Optional: Parts for organizing chapters
  # parts:
  #   - part: "Part I: Introduction"
  #     chapters:
  #       - index.qmd
  #       - intro.qmd
  #   - part: "Part II: Main Content"
  #     chapters:
  #       - chapter1.qmd
  #       - chapter2.qmd

format:
  html:
    theme: cosmo
    cover-image: cover.png
    favicon: favicon.ico
    
  pdf:
    documentclass: scrreprt
    include-in-header: header.tex
    
  epub:
    cover-image: cover.png

link-citations: true

# Optional: Additional metadata
bibliography: 
  - references.bib # the intro and discussion references
  - model_time/references.bib  
  - empirical_paper/references.bib
  - violence/references.bib
  - bbs/references.bib

# Optional: Execute options
execute:
  freeze: auto
