---
title: "General discussion"
format:
  pdf:
    include-in-header: header.tex
#bibliography: references.bib
editor: visual

#csl: procb.csl
keeptex: true
toc: true
bibliography: references.bib
---

## Summary of the findings

In the chapters that precede, I have presented the desperation threshold model (DTM), investigated its predictions in multiple domains, and assessed its empirical plausibility. I have used multiple methodologies: numerical optimisation and agent-based modeling (Chapter 2), analytical mathematics (Chapter 3), data analysis (Chapter 4) and literature review (Chapter 5). These results are part of a broader research program that now includes many more persons. Thus, this dissertation is an interim report of a continuing and expanding project.

The origin of the project is outside this dissertation, as it was published before I was a PhD student. In this paper, Daniel Nettle and I showed that the desperation threshold (DT) can account, through risk taking, for the higher property crime and lower trust found in deprived populations. The second chapter extends the DTM to violent crime, which is by definition not directly economically motivated. My model shows that the DT, combined with the assumption that violence sends a toughness signal, can explain why violent crime is also high in deprived or unequal populations. Interestingly, the model predicts that everyone should be violent in a deprived population, but that only desperate agents should commit property crime. The model can also account for the persistence of violence in neighbourhoods, even after economic conditions have improved.

The third chapter extends the scope of the DTM from risk taking to time discounting. I present four different scenarios that capture different versions of the DT in an intertemporal context, varying the consequences of desperation on future utility. In all scenarios, the model predicts a higher time discounting when the agent is close to the DT. It also predicts higher patience when she is safe from the DT in the short term but not the long term, which echoes the idea of 'middle class values' in social sciences.

The fourth chapter is the only empirical analysis strictly speaking. I use secondary data that Daniel Nettle had collected to study the effect of poverty on mental health, that includes measures of resources and measures of risk taking through hypothetical gambles. I translate the DTM into clear-cut empirical predictions. First, risk taking should follow a U-shape of resources. Second, a fuzzier prediction: risk taking should vary more in deprived populations, both between people and within-person over time. I find partial support for the first prediction: I obtain the U-shape with subjective resources and a broken-stick model, but not with objective resources or a polynomial model. The support for the second prediction is unequivocal, and the effect is very large. Risk taking is clearly polarized among the participants with low income: both extreme risk taking and extreme risk avoidance are more frequent.

The fifth chapter is the less technical, but the most ambitious one. It presents a sort of manifesto for the DTM. I start from the paradoxical relationship between poverty and risk taking: theories and empirical results in social sciences predict both an increase and a decrease of risk taking in situations of poverty. I present the DTM as an answer to this paradox. I present it in its purest form. I highlight and justify its core assumptions: there is a utility 'cliff', and a 'rock bottom'. I derive its main predictions and replace it within the broader social sciences, showing that the DTM has many antecedents in diverse disciplines. Then, I review empirical evidence relevant to assess the DTM, using results from diverse disciplines and methodologies. Finally, I expose the population-level implications of the DTM, the remaining issues and an agenda for DTM research.

The last chapter already discusses at length the state and the future of the DTM research agenda. I will not repeat those conclusions here, but simply close with just a few reflections to situate this thesis within the broader social sciences.

\

## Concluding remarks

### Social life and poverty

In his introduction of The code of the street, that has been so useful for this dissertation, @anderson2000 starts by giving the reader a walk "Down Germantown Avenue", which "provides an excellent cross section of the social ecology of a major American city" (p. 26). As he exits the rich Chestnut Hill and progresses further south, Anderson observes not just a change of landscape, but also of behaviour: "There are businesses that cater mostly to the criminal class, such as pawnshops and beeper stores. Pawnshops are, in a sense, banks for thieves; they are places where stolen goods can be traded for cash, few questions asked. Check-cashing exchanges, which continue to be a common sight, also ask few questions, but they charge exorbitant fees for cashing a check. As in Chestnut Hill, merchandise is often displayed on the sidewalk, but here it is under the watchful eye of unsmiling security guards. The noise level here is also much louder. Cars drive by with their stereo systems blaring. Farther down, young people walk down the street or gather on someone's stoop with their boom boxes vibrating, the bass turned way up. On adjacent streets, open-air drug deals occur, prostitutes ply their trade, and boys shoot craps, while small children play in trash-strewn abandoned lots." (p.45).

Most readers will recognize what Anderson describes. Social life is spectacularly different in deprived populations, which tend, among other things, to have low trust, low cooperation, high crime and high violence [@nettle2015]. Social scientists, however, tend to favor holistic explanations -- such as the idea that poverty provokes a social dislocation [@wilson2012], or disrupts 'collective efficacy' [@sampson2012] -- rather than attributing those social outcomes to individual decisions. Put otherwise, social scientists tend to resist opening the black box of poverty. This would risk, they fear, blaming people in poverty, and essentialising them as intrinsically and irretrievably different. Social scientists often prefer to believe, as @banerjee2004 ironically puts it, that "the poor \[are\] just like you and me except in that they have less money" (p. 129).

My dissertation aims at showing that, on the contrary, a reductionist and rational choice approach is possible, desirable and non-stigmatizing. While methodological individualism might not be relevant to explain the existence of poverty [@brady2023], it is essential to understand the behavioral consequences of poverty: people do not choose to be in poverty, but they decide whether to trust their neighbours, or to take a payday loan. Viewing these decisions as state-dependent rational choices allows us to explain them at the individual level, without portraying people in poverty as fundamentally different. They simply face different constraints, which call for different actions. Actually, people commonly explain these decisions by saying that people 'have no choice', that their 'back is against a wall'. What people actually mean, I think, is that the alternative choice (not taking a payday loan, not committing a crime) produces an awful situation. This is precisely the focus of the desperation threshold (DT): understanding decisions under extreme constraint. This is not a simple change framing: the DTM shows that the predictions are actually not so simple.

### The desperation threshold: an obvious, but disturbing idea

Thus, my dissertation shows that many social outcomes typical of deprived populations can be attributed to rational individual decisions, and in particular to the struggle to make ends meet. As I argued in the introduction, this idea is intuitive, and we spontaneously invoke it when we observe the decisions of people in poverty. What this verbal model misses, and what the formal modeling reveals, is that the effect of the threshold is rarely trivial. In most cases, the threshold does not produce monotonic relationships between economic resources and behavior. People should take risks when below the threshold, but avoid risk when just above. People should discount the future around the threshold, but on the contrary save resources when they are safe in the short term but not in the longer term.

More broadly, my dissertation reveals that the DT has disturbing effects on social life. It paints a much messier world than the traditionally used concave utility functions. It is, I believe, especially clear when viewed from a population-level perspective. It can account for clichés -- crime is more frequent in deprived populations -- but it also shows what is simplistic about them: some people take extreme risks like crime, while most of them avoid risk, and are especially unlikely to commit crime. Our model and our empirical findings in Chapter 4 suggest that a deprived neighbourhood brings together people with much to lose and others with very little.. Furthermore, since levels of resources are not public and a minor change in resources can trigger a massive change in behavior, people in deprived populations probably know less well what to expect from others. This can have intriguing emerging effects, like the runaway of violence we study in Chapter 2.

\

### What next?

I believe that we are only starting to perceive the full consequences of the DT. In the future, I hope to build models to study the effect of the DT decision to spend time in work or in leisure, for instance, or its possible effects on voting. I am also interested in elaborating the idea that we float in Chapter 5: if a greedy landlord or company manager is aware of the DT, she should set the rent or the wages just above the threshold, in order to maximise profit while avoiding the risk of a catastrophe. More broadly, I think the field should build more formal models to justify or invalidate the profusion of verbal theories we have about behaviours in situations of poverty. For too long, the field has relied on verbal theories like the "fast-slow continuum" or the "I need to eat today" intuition (see Chapter 3). It is becoming increasingly clear that these theories are shaky, and the field is, fortunately, I hope, moving toward more formalisation.

However, I fear that there is a risk of overusing the desperation threshold concept. In the Introduction, I have pledged to use the threshold in an abductive manner -- to explain empirical regularities -- rather than a deductive one. Recently, I have found myself and my colleagues increasingly eager to use it deductively -- after spending half a decade on this idea, it starts to feel like the DT actually exists. Perhaps this is justified, given that we now have strong reasons to believe the DT offers a compelling account of decision-making under poverty. But the risk of taking the DTM too seriously and forgetting that it is a toy model worries me. Its abstractness and generalizability makes it possible to apply it to most aspects of social life, but when you only have a hammer, everything looks like a nail. The precise scope of the DTM remains unclear to me, but it must have clearer limits.

The proper next steps should probably be empirical. My Chapter 4 is just a start, and the clear findings that we report -- a polarization of risk taking among low-income participants -- could easily be replicated in other datasets. Another question remains. The DTM is not a psychological model but a behavioural one. It only predicts that some behaviours are more frequent in some situations, but is agnostic about psychological states. Nevertheless, the opposite behaviors the DTM predicts on either side of the threshold must stem from different psychological processes and emotional states.

My colleague Arnaud Wolff has recently run qualitative interviews to understand the experiences of people in poverty, and to analyse them in the light of the DTM. In his sample, he finds that most people find ways to make ends meet, in general by budgeting or asking help from others in their social network. The world is, of course, more complex than the DTM represents it, and decisions are embedded in social networks. This is something I had entirely missed when elaborating the models. I think it might have been for the best, as this helped phrasing the DTM in its purest and most detached way. But the DTM may now be ripe for adaptation to better fit social realities. This makes me wonder more generally about my position, as a social scientist born far from poverty, who has spent his whole life in rich neighbourhoods. This has led me to ignore obvious facts, like the key role of social support in making ends meet. But I believe my inexperience of poverty and my emotional distance with it has also led me to always be surprised by empirical findings, and to approach them as puzzles rather than self evident. This has probably helped me to propose a formalisation of commonsensical intuitions, and to see their previously unseen consequences. I am also grateful to my supervisors, in particular Willem Frankenhuis, for having kept me on a tight leash on my writing and pushed me toward writing in a non-stigmatizing and non-essentializing way. I doubt I have entirely succeeded in that regard, but I would undoubtedly have failed without their guidance.
