# Summary  {.unnumbered}

In this dissertation, I propose the desperation threshold model, which seeks to explain decisions in situations of poverty as rational ones. The model assumes that people in poverty aim at staying above a "desperation threshold" -- a critical amount of resources that represents their basic needs. Throughout the dissertation, I show that this assumption can explain several behavioral patterns associated with poverty -- and with economic inequality at the population level. I then try to assess its empirical validity. I explore this idea in two modelling chapters, one empirical chapter using secondary data, and an integrative literature review chapter. In the first modeling chapter (Chapter 2), I show that the desperation threshold can account not only for the high proportion of property crime in deprived or unequal populations, but also for the frequency of violent crime, as a toughness signal to deter exploitation. In the second modeling chapter (Chapter 3), I show that the desperation threshold generates elevated time discounting when basic needs are on the line. Chapter 4 aims at testing the model's prediction empirically. I show that the empirical literature is currently split, with studies predicting and finding either an increase or a decrease of risk taking in situations of poverty. I propose that the desperation threshold model can reconcile these seemingly contradictory findings. I derive testable predictions from the model, and test them on secondary survey data from France and the UK. I obtain partial support for a U-shape between resources and risk taking, but a clear polarizing effect: both risk taking and risk avoidance are more frequent among the poorer participants. In the integrative review chapter (Chapter 5), I give more perspective on the desperation threshold. I first state the model in its purest form, highlight and justify its core assumptions. I then review the empirical evidence from diverse fields and methods, relevant to test the validity desperation threshold model. I find that similar models -- under different names -- have been proposed and tested across several social and biological science disciplines, though their full implications and explanatory potential have rarely been recognized. I conclude that the desperation threshold model, along its intellectual antecedents, has promising empirical support, and is already a fruitful paradigm for the study of poverty.
\newpage

# Samenvatting  {.unnumbered}
In dit proefschrift stel ik het wanhoopsdrempelmodel voor, dat probeert beslissingen in situaties van armoede te verklaren als rationele beslissingen. Het model gaat ervan uit dat mensen in armoede ernaar streven om boven een “wanhoopsdrempel” te blijven -- een kritische hoeveelheid middelen die hun basisbehoeften vertegenwoordigt. Door het proefschrift heen laat ik zien dat deze aanname verschillende gedragspatronen kan verklaren die geassocieerd worden met armoede -- en met economische ongelijkheid op het niveau van de bevolking. Vervolgens probeer ik de empirische geldigheid ervan te beoordelen. Ik verken dit idee in twee modelleringshoofdstukken, een empirisch hoofdstuk met secundaire gegevens en een integratief hoofdstuk over literatuuronderzoek. In het eerste modelleringshoofdstuk (hoofdstuk 2) laat ik zien dat de wanhoopsdrempel niet alleen het hoge aandeel van vermogenscriminaliteit in achtergestelde of ongelijke bevolkingsgroepen kan verklaren, maar ook de frequentie van geweldsdelicten, als een hardheidssignaal om uitbuiting af te schrikken. In het tweede modelleringshoofdstuk (hoofdstuk 3) laat ik zien dat de wanhoopsdrempel een verhoogde tijddiscontering genereert wanneer basisbehoeften op het spel staan. Hoofdstuk 4 richt zich op het empirisch testen van de voorspelling van het model. Ik laat zien dat de empirische literatuur op dit moment verdeeld is, met studies die ofwel een toename of een afname van het nemen van risico's in situaties van armoede voorspellen en vinden. Ik stel voor dat het wanhoopsdrempelmodel deze schijnbaar tegenstrijdige bevindingen met elkaar kan verzoenen. Ik leid testbare voorspellingen uit het model af en test ze op secundaire onderzoeksgegevens uit Frankrijk en het Verenigd Koninkrijk. Ik krijg gedeeltelijke ondersteuning voor een U-vorm tussen middelen en risicobereidheid, maar een duidelijk polariserend effect: zowel risicobereidheid als risicovermijding komen vaker voor bij de armere deelnemers. In het integrerende overzichtshoofdstuk (hoofdstuk 5) geef ik meer perspectief op de wanhoopsdrempel. Eerst geef ik het model in zijn meest zuivere vorm weer, waarbij ik de belangrijkste aannames benadruk en rechtvaardig. Vervolgens bekijk ik het empirisch bewijs uit verschillende velden en methoden die relevant zijn om de geldigheid van het wanhoopsdrempelmodel te testen. Ik ontdek dat soortgelijke modellen - onder verschillende namen - zijn voorgesteld en getest in verschillende disciplines van de sociale en biologische wetenschappen, hoewel hun volledige implicaties en verklarend potentieel zelden zijn erkend. Ik concludeer dat het wanhoopsdrempelmodel, samen met zijn intellectuele antecedenten, veelbelovende empirische ondersteuning heeft en al een vruchtbaar paradigma is voor de studie van armoede.

